name: Backend CI

on:
  push:
    paths:
      - 'outilmaria-back/**'
  pull_request:
    paths:
      - 'outilmaria-back/**'
  workflow_dispatch: {}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: outilmaria-back
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: outilmaria-back/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 pytest

      - name: Lint & format check
        run: |
          black --check .
          isort --check-only --profile black .
          flake8 .

      - name: Run tests
        run: pytest -q

  deploy:
    needs: lint-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "outilmaria-back/*"
          target: "/home/deployuser/app"

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            set -euo pipefail
            cd /home/deployuser/app
            docker compose down || docker-compose down
            docker compose up -d --build || docker-compose up -d --build
